Update docs to avoid installing grunt-cli
materializecss/materialize pull request #29
Opened 2020-09-19 22:01 UTC by nekonenene

## Proposed changes

Developers don't need to install grunt-cli because we already installed into node_modules via `npm install`. Now, I replaced commands in docs using `npm` instead of `grunt`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [ ] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-09-20 11:27 UTC, Smankusors approved these changes
this seems better IMO, what do you think? @DanielRuf

2020-09-20 11:55 UTC, DanielRuf requested changes

2020-09-20 11:55 UTC, DanielRuf commented on CONTRIBUTING.md
> +After `npm install`, you can run `npm test` and it will run the tests. If you get an errors and have not made any changes, it means you have not installed the proper dependencies.
an errors => any errors

2020-09-20 12:09 UTC, nekonenene commented on CONTRIBUTING.md
> +After `npm install`, you can run `npm test` and it will run the tests. If you get an errors and have not made any changes, it means you have not installed the proper dependencies.
Thanks! Fixed.

2020-09-20 12:11 UTC, DanielRuf approved these changes

2020-09-20 12:12 UTC, DanielRuf commented
Thanks, this is much better than before.

2020-09-20 12:13 UTC, merged

2020-09-20 22:51 UTC, DanielRuf commented
@nekonenene you should have received an invitation for the materializecss org and to the members team of it.

You can see and accept it at https://github.com/materializecss

2020-09-21 02:33 UTC, nekonenene commented
@DanielRuf 
Thanks! I joined. 💪