Update datepicker & timepicker "container" option to allow being specified the same way
materializecss/materialize pull request #69
Opened 2021-02-12 03:36 UTC by Cerothen

## Proposed changes
The datepicker and timepicker have containers that are specified in different ways (datepicker = element, timepicker = document query selector string). These changes allow both to have the container specified by either an element or a query string for both elements to maintain backward compatability while also harmonizing the entry method.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:
- [X] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2021-02-13 20:43 UTC, nicknickel approved these changes
LGTM

2021-02-14 13:33 UTC, Smankusors requested changes
I think the doc (jade/page-contents/pickers_content.html) for both the date picker and time picker need to be updated.

For example, in the date picker, the row with "container" in the name column, can be updated like this

| Name | Type | Default | Description
| -- | -- | -- | -- |
| container | Element \|\| String | null | Specify a DOM element to render the calendar in, or a selector string for a DOM element to render the calendar in. By default it will be placed before the input. |

And in the time picker doc, just replace "calendar" with "time picker" in the description.

2021-04-21 21:39 UTC, DanielRuf commented
> I think the doc (jade/page-contents/pickers_content.html) for both the date picker and time picker need to be updated.
>
> For example, in the date picker, the row with "container" in the name column, can be updated like this
>
> And in the time picker doc, just replace "calendar" with "time picker" in the description.

@Cerothen can you update the files according to the review by @Smankusors?

2021-05-09 04:07 UTC, Smankusors approved these changes

2021-05-10 06:35 UTC, merged

2021-05-10 09:27 UTC, Smankusors commented
@Cerothen Thanks for the PR

I also invited you to the materializecss org. Welcome! 😃