Disable outline on focussed dropdown-trigger
materializecss/materialize pull request #73
Opened 2021-03-08 12:24 UTC by JayDijkstra

## Proposed changes

As stated in https://github.com/materializecss/materialize/issues/72 the browser puts an ugly outline for an dropdown-trigger which recieves the :focus state. To fix this disable the outline for focussed .dropdown-trigger elements.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:

- [x] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-03-08 16:56 UTC, wuda-io approved these changes
Looks good to me 👍

2021-03-09 01:22 UTC, Smankusors commented
hmm wait wait, for accessbility reasons, is this will be a temporary solution? for someone who only use keyboard, they will find this difficult

2021-03-09 10:14 UTC, DanielRuf commented
> hmm wait wait, for accessbility reasons, is this will be a temporary solution? for someone who only use keyboard, they will find this difficult

Exactly. We should not remove but style this.

2021-03-09 10:15 UTC, DanielRuf commented on sass/components/_dropdown.scss
> +    outline: 0;
Please see https://www.google.com/search?channel=fs&client=ubuntu&q=outline+0+bad why this is a bad practice to remove it in general.

2021-03-09 10:46 UTC, Smankusors requested changes
sorry, but the PR should be about fixing the outline style, not disabling it entirely...

---

Edit : I'm just realised the original issue is not about the styling. But more about the style being applied without using keyboard.

2021-03-09 19:24 UTC, wuda-io commented
I understand that navigating with keyboard only is difficult. But as far as i know, does not even a single button has a focus style, so i thought this would be no big deal.
I think we should disable the outline style, but change the focus to a slightly different color style. But this would be another issue i guess.
Best regards

2021-03-11 07:39 UTC, wuda-io commented
Yea I just thought again about your concern and I must admit that you are right... :P
I looked into the main page of materializecss and there the Focus Style works.
What should we do now?
Greets

2021-03-14 10:53 UTC, Smankusors commented
I'm sorry, but I will close this PR now.

If you decided to fix the bug mentioned in #72, feel free to create a new PR about it. 😉

2021-03-14 10:53 UTC, closed without merging